# Generated by Django 4.2.11 on 2024-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idDisplay", models.CharField(max_length=10)),
                ("title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
