# Generated by Django 4.2.11 on 2024-07-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="problem",
            name="idDisplay",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
