# Generated by Django 4.2.11 on 2024-07-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_problem_level_alter_problem_iddisplay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="idDisplay",
        ),
        migrations.AlterField(
            model_name="problem",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
