# Generated by Django 5.0.7 on 2024-07-15 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_problem_iddisplay_alter_problem_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("secret", models.UUIDField(default=uuid.uuid5, editable=False)),
                ("problemId", models.CharField(max_length=10)),
                ("language", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=10)),
                ("source", models.TextField()),
                ("judgeResult", models.CharField(max_length=3)),
                ("errorLogs", models.TextField()),
            ],
        ),
    ]
