# Generated by Django 5.0.7 on 2024-07-15 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="secret",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
