# Generated by Django 5.0.7 on 2024-07-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_submission_id_alter_submission_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="errorLogs",
            field=models.TextField(null=True),
        ),
    ]
