# Generated by Django 5.0.7 on 2024-07-15 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_submission_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="problemId",
        ),
        migrations.AddField(
            model_name="submission",
            name="problem",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.problem"
            ),
            preserve_default=False,
        ),
    ]
