# Generated by Django 5.0.7 on 2024-07-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_submission_problemid_submission_problem"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stdin", models.TextField(default="")),
                ("stdout", models.TextField()),
                ("compileFlags", models.TextField(default="")),
                ("runFlags", models.TextField(default="")),
                ("timeLimit", models.IntegerField(default=-1)),
                ("memoryLimit", models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="config",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.runtimeconfig",
            ),
            preserve_default=False,
        ),
    ]
