# Generated by Django 5.0.7 on 2024-07-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_runtimeconfig_problem_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="config",
        ),
        migrations.AddField(
            model_name="problem",
            name="compileFlags",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="memoryLimit",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="problem",
            name="runFlags",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="stdin",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="stdout",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="timeLimit",
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name="RuntimeConfig",
        ),
    ]
