# Generated by Django 5.0.7 on 2024-07-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_problem_config_problem_compileflags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="compileFlags",
        ),
        migrations.AlterField(
            model_name="problem",
            name="memoryLimit",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="runFlags",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="timeLimit",
            field=models.IntegerField(null=True),
        ),
    ]
