# Generated by Django 5.0.7 on 2024-07-20 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_secret_submission_viewid"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="summittedOn",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
