# Generated by Django 5.1.2 on 2025-03-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_submission_summittedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='summittedOn',
            new_name='submittedOn',
        ),
    ]
